import { 
  render as testingLibraryRender, 
  RenderOptions,
  screen,
  fireEvent,
  waitFor,
  act,
  cleanup,
  renderHook,
  prettyDOM,
  logRoles,
  within,
  getByRole,
  getByLabelText,
  getByPlaceholderText,
  getByText,
  getByDisplayValue,
  getByAltText,
  getByTitle,
  getByTestId,
  getAllByRole,
  getAllByLabelText,
  getAllByPlaceholderText,
  getAllByText,
  getAllByDisplayValue,
  getAllByAltText,
  getAllByTitle,
  getAllByTestId,
  queryByRole,
  queryByLabelText,
  queryByPlaceholderText,
  queryByText,
  queryByDisplayValue,
  queryByAltText,
  queryByTitle,
  queryByTestId,
  queryAllByRole,
  queryAllByLabelText,
  queryAllByPlaceholderText,
  queryAllByText,
  queryAllByDisplayValue,
  queryAllByAltText,
  queryAllByTitle,
  queryAllByTestId,
  findByRole,
  findByLabelText,
  findByPlaceholderText,
  findByText,
  findByDisplayValue,
  findByAltText,
  findByTitle,
  findByTestId,
  findAllByRole,
  findAllByLabelText,
  findAllByPlaceholderText,
  findAllByText,
  findAllByDisplayValue,
  findAllByAltText,
  findAllByTitle,
  findAllByTestId,
} from '@testing-library/react';
import { ReactElement } from 'react';

// Custom render function that can be extended with providers if needed
export function renderWithProviders(
  ui: ReactElement,
  options?: Omit<RenderOptions, 'wrapper'>
) {
  return testingLibraryRender(ui, options);
}

// Re-export everything explicitly from testing-library/react
export {
  testingLibraryRender,
  screen,
  fireEvent,
  waitFor,
  act,
  cleanup,
  renderHook,
  prettyDOM,
  logRoles,
  within,
  getByRole,
  getByLabelText,
  getByPlaceholderText,
  getByText,
  getByDisplayValue,
  getByAltText,
  getByTitle,
  getByTestId,
  getAllByRole,
  getAllByLabelText,
  getAllByPlaceholderText,
  getAllByText,
  getAllByDisplayValue,
  getAllByAltText,
  getAllByTitle,
  getAllByTestId,
  queryByRole,
  queryByLabelText,
  queryByPlaceholderText,
  queryByText,
  queryByDisplayValue,
  queryByAltText,
  queryByTitle,
  queryByTestId,
  queryAllByRole,
  queryAllByLabelText,
  queryAllByPlaceholderText,
  queryAllByText,
  queryAllByDisplayValue,
  queryAllByAltText,
  queryAllByTitle,
  queryAllByTestId,
  findByRole,
  findByLabelText,
  findByPlaceholderText,
  findByText,
  findByDisplayValue,
  findByAltText,
  findByTitle,
  findByTestId,
  findAllByRole,
  findAllByLabelText,
  findAllByPlaceholderText,
  findAllByText,
  findAllByDisplayValue,
  findAllByAltText,
  findAllByTitle,
  findAllByTestId,
};

export { renderWithProviders as render };