name: Deploy Storybook to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --no-fund
      
    # Cache Storybook build for faster deployments
    - name: Cache Storybook build
      uses: actions/cache@v4
      with:
        path: storybook-static
        key: storybook-deploy-${{ runner.os }}-${{ hashFiles('src/**/*', '.storybook/**/*', 'package-lock.json') }}
        restore-keys: |
          storybook-deploy-${{ runner.os }}-
          
    - name: Build Storybook
      run: npm run build-storybook
      env:
        NODE_ENV: production
        NODE_OPTIONS: '--max-old-space-size=4096'
        GENERATE_SOURCEMAP: false
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './storybook-static'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4